/****** 2. DETALLE DE UNA ORDEN POR [ID] ******/
SELECT 
	   od.[ID_ORDER_HEADER],
       od.[ID_EC_PRODUCT],
       od.[NAME],
       od.[PRODUCT_ID],
       od.[QUANTITY],
       od.[QUANTITY_DISPATCHED],
       od.[SUBTOTAL],
       ( CASE
           WHEN ECP.PRODUCT_TYPE IN ( 'S', 'V2' ) THEN OD.[SKU]
           ELSE ECP.SKU_FATHER
         END )                    AS PRODUCT_CODE,
       od.[PRICE]                 AS EC_PRICE,
       oh.[ID],
       oh.[ID_ECOMMERCE],
       Isnull(oh.[TO_INVOICE], 0) AS [TO_INVOICE],
       oh.RECEIVED_DATE,
       oh.PAYMENT_METHOD,
       oh.PAYMENT_METHOD_TITLE,
       oh.CODE_TRANSACTION,
       oh.CUSTOMER_NAME,
       oh.CUSTOMER_LAST_NAME,
       oh.IDENTIFICATION_CARD,
       oh.ADDRESS,
       oh.TOTAL,
	   Cast(Round(oh.TOTAL,2 ) as decimal(18,2)) TOTAL_ROUDED,
       oh.TOTAL_TAX,
       oh.DELIVERY_COST,
       oh.NOTA_CLIENTE,
       oh.TOTAL_PRODUCT
--,(SELECT TOP(1) PRICE_RETAIL 
--     FROM VISION_PRIMAVERA.dbo.PRODUCT p 
--     WHERE p.PRODUCT_CODE = [dbo].[f_GP_GetProductCode](OD.SKU)) AS PRICE_VISION
FROM   [VISION_WEB].[dbo].[GP_EC_ORDER_DETAIL] OD
       INNER JOIN [VISION_WEB].[dbo].GP_EC_ORDER_HEADER oh
               ON oh.ID = od.ID_ORDER_HEADER
       INNER JOIN [VISION_WEB].[dbo].GP_EC_PRODUCT ECP
               ON OD.SKU = ECP.SKU
WHERE  ID_ORDER_HEADER 
	 		--		=  7654
	--in  ( 7737, 7743, 7740, 7732, 7731 ) 

	--=71
--	=7551



	in (SELECT top 300 [ID]        
FROM   [VISION_WEB].[dbo].GP_EC_ORDER_HEADER oh
WHERE  IS_DISPATCHED = 1 
 ORDER  BY RECEIVED_DATE DESC 
        )

--	ID_ORDER_HEADER	ID_EC_PRODUCT	NAME	PRODUCT_ID	QUANTITY	QUANTITY_DISPATCHED	SUBTOTAL	PRODUCT_CODE	EC_PRICE	ID	ID_ECOMMERCE	TO_INVOICE	RECEIVED_DATE	PAYMENT_METHOD	PAYMENT_METHOD_TITLE	CODE_TRANSACTION	CUSTOMER_NAME	CUSTOMER_LAST_NAME	IDENTIFICATION_CARD	ADDRESS	TOTAL	TOTAL_TAX	DELIVERY_COST	NOTA_CLIENTE	TOTAL_PRODUCT
--7737	341252	Atomizador Plástico de 32 Onzas (950 Ml)	797052	1	1	1.8900	1332959	1.89	7737	1629551	0	2023-05-26 12:30:47.537	nmi_gateway_woocommerce_credit_card	Tarjeta de Crédito	8373559041	JULIO	TRELLES		AVENIDA LA PAZ PLAZA 100	2.0223	0.1323	0.00	OC-05959	1




-- 7654

--64101